fix: stopwordsiso requires setuptoosl
or it will raise errors:

    Exception occurred:
      File "/usr/local/lib/python3.12/site-packages/stopwordsiso/_core.py", line 8, in <module>
        STOPWORDS_FILE = pkg_resources.resource_filename(name, "stopwords-iso.json")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'pkg_resources' has no attribute 'resource_filename'
    The full traceback has been saved in ***.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!